# production: &production
  # twitter:
  #   key: 
  #   secret: 
  # facebook:
  #   key: xxxxxxxxxxx
  #   secret: XXXXXXXXXXXXXXXXXXXXXXXXX
  # google:
  #   key: 535937584258-jfnt6cgo2aeprpd8qmeh0o4s8hksb64q.apps.googleusercontent.com
  #   secret: 14CJbF_Awxbwe_OA1Apcbt1v

# development: &development
#   <<: *production
#   facebook:
#     key: xxxxxxxxxxx
#     secret: XXXXXXXXXXXXXXXXXXXXXXXXX

# test:
#   <<: *development